const fs = require("node:fs");
const path = require("node:path");

const GENERATED_HEADER = "// AUTO-GENERATED BY AutoBD. DO NOT EDIT.";

function isGeneratedFile(filePath) {
  const stat = fs.lstatSync(filePath);
  if (!stat.isFile()) return false;

  const expected = Buffer.from(GENERATED_HEADER);
  const actual = Buffer.alloc(expected.length);
  const file = fs.openSync(filePath, "r");
  try {
    return (
      fs.readSync(file, actual, 0, actual.length, 0) === expected.length &&
      actual.equals(expected)
    );
  } finally {
    fs.closeSync(file);
  }
}

function assertGeneratedTarget(filePath) {
  try {
    fs.lstatSync(filePath);
  } catch (error) {
    if (error.code === "ENOENT") return;
    throw error;
  }
  if (!isGeneratedFile(filePath)) {
    throw new Error(
      `AutoBD will not overwrite a non-generated file: ${filePath}`,
    );
  }
}

function prepareOutputDirectory(outputDir, mode) {
  if (mode === "full" && fs.existsSync(outputDir)) {
    removeGeneratedFiles(outputDir);
  }
  fs.mkdirSync(outputDir, { recursive: true });
}

function removeGeneratedFiles(directory) {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const filePath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      removeGeneratedFiles(filePath);
    } else if (entry.isFile() && isGeneratedFile(filePath)) {
      fs.rmSync(filePath);
    }
  }
}

function assertConsumerOutput(projectRoot, outputDir) {
  const projectPath = fs.realpathSync(projectRoot);
  let existingPath = outputDir;
  while (!fs.existsSync(existingPath)) {
    const parent = path.dirname(existingPath);
    if (parent === existingPath) break;
    existingPath = parent;
  }
  const realOutput = path.resolve(
    fs.realpathSync(existingPath),
    path.relative(existingPath, outputDir),
  );
  const relative = path.relative(projectPath, realOutput);
  if (
    !relative ||
    relative === ".." ||
    relative.startsWith(`..${path.sep}`) ||
    path.isAbsolute(relative) ||
    relative.split(path.sep).includes("node_modules")
  ) {
    throw new Error(
      `Output directory must be inside the consumer project and outside node_modules: ${outputDir}`,
    );
  }
  if (fs.existsSync(outputDir)) {
    if (fs.lstatSync(outputDir).isSymbolicLink()) {
      throw new Error(`AutoBD output cannot be a symbolic link: ${outputDir}`);
    }
    assertNoSymlinks(outputDir);
  }
}

function assertNoSymlinks(directory) {
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const filePath = path.join(directory, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(
        `AutoBD output cannot contain a symbolic link: ${filePath}`,
      );
    }
    if (entry.isDirectory()) assertNoSymlinks(filePath);
  }
}

module.exports = {
  GENERATED_HEADER,
  assertConsumerOutput,
  assertGeneratedTarget,
  isGeneratedFile,
  prepareOutputDirectory,
};
